version: 0.2

phases:
  pre_build:
    commands:
    - ${aws ecr get-login --no-include-email --region us-east-1}
    - REPOSITORY_URI=001273462887.dkr.ecr.us-east-1.amazonaws.com/my-repository
    - IMAGE_NAME=$REPOSITORY_URI/analytics-app
  build:
    commands:
    - echo "HELP"
    - docker build -t $REPOSITORY_URI/$ANALYTICS_APP:latest
    - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CODEBUILD_BUILD_NUMBER
    - echo "DONE?"
  post_build:
    commands:
    - docker push $IMAGE_NAME:latest
    - docker push $IMAG_NAME:$CODEBUILD_BUILD_NUMBER