apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap-local
data:
  DB_NAME: postgresql
  DB_USER: myuser
  DB_HOST: "127.0.0.1"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-password
type: Opaque
data:
  password: bXlwYXNzd29yZA==